# Generated by Django 5.1.1 on 2024-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_category_tag_alter_post_options_remove_post_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='posts', to='blog_app.tag', verbose_name='Теги'),
        ),
    ]
